### ISSUE TITLE
minimum_permissions

### ISSUE THREAD

**Issue by Jakke17** [RogerSelwyn/MS365-Calendar#10]
Hey,

I have an O365 payed family account.
I've set permissions on the Azure page and followed your instructions.

After I add the returned URL, it shows the error minimum permissions?
see screenshot

thanks for the help

<img width="590" alt="Scherm­afbeelding 2024-07-18 om 14 11 44" src="https://github.com/user-attachments/assets/8071ddaf-4dbb-41de-9a85-5c4d78af9baf">

**Comment by RogerSelwyn** [comment]
To access a shared mailbox calendar by configuring shared_mailbox you need to provide that permission. Have you done so?

**Comment by Jakke17** [comment]
Roger,

thank you for the quick response.
Where can I set that permission? Azure portal? O365 admin portal.
These are my permissions.

<img width="1026" alt="image" src="https://github.com/user-attachments/assets/336514ed-8988-4de1-a544-eed9dbe84856">

Greetz 
Jan

**Comment by RogerSelwyn** [comment]
Might be a bug, I’ll check

**Comment by RogerSelwyn** [comment]
Might be worth trying delete the token, so it reauthenticates from scratch

**Comment by Jakke17** [comment]
I will give that a go.
Here are my logs

This error originated from a custom integration.

Logger: custom_components.ms365_calendar.classes.permissions
Source: custom_components/ms365_calendar/classes/permissions.py:59
integration: Micosoft 365 - Calendar (documentation, issues)
First occurred: 14:06:17 (1 occurrences)
Last logged: 14:06:17

Minimum required permissions: 'Calendars.Read.Shared'. Not available in token 'ms365_calendar_JanDebocCAL.token' for account 'JanDebocCAL'.

**Comment by RogerSelwyn** [comment]
You can look in the token and see if the permission is listed there. If it isn’t, then you need to reauthenticate.

**Comment by Jakke17** [comment]
Still the same error.
Delete the token with file editor

**Comment by Jakke17** [comment]
this is my token.

{
 "token_type": "Bearer",
 "scope": [
  "User.Read"
 ],
 "expires_in": 3600,
 "ext_expires_in": 3600,
 "access_token": "EwCAA8l6BAAUbDba3x2OMJElkF7gJ4z/VbCPEz0AAXVCMawGPzZrbmtN6nz/6sUclG7cBbkPcXLwfopN8r9FVCc8diERZOOoS3sZ3mTdM8y7FoPlHueqjw0fLTyCthgkMbxDBPuLDLOFFlRE6X4WgXQMoBw8Mz0Da0B41J32BgywVuKPtcbsN0YggUtIerooCbyX7t18nFfuakojdKuA77AEJdNvBDplCNaStmXjUMuPWMndzowLmHpR7zzpMl1hrUo6mNf3MlkTLYVaZ3eLgiLqVODTwy47mCEe20JahL9mHCg+a0HLO33//TFSqqLzBYKeb1eYXCNpg+mJL38mzu/QgqzxJ+qlW9RYTCu+BoEcK/vMUi9ksyxVLqR5qhoDZgAACDY+UhFZNx1GUAJXCreJx2je7QZhCYc9BSOj8MshNxVAfqGK1I2NC2tzYukWA7aYrG/DVvzm6BlPiPji8msYLyOsBOUIGGLe5gbepLejBrUmX0xyjbKplhlhNYL2Boyr3VLpSKpZ32S2UvhFfnPbESMez8HC5QGUSVoK9wuAXKwk0ZDtFrDT8OSKBo6Z5lVh03yCVlsuRqBs+zlL0gQvYwT6kFy0y4AHtJ5230j0T50rsKFPI/BwQE74n0o2q3lmbhE9UoH+EAun/ZZe3WvQ0vaEcmLJ5+LgDA5tWeMf0KfnHWgjMwPB0svY1poqpL/+rCgU/7XQcHYXJvaSU2ZTfg/uIclTcbg/8QuhoOBQbEBI9/sdikmuz7kO1Iqzi/qZS1oxQtWYJQsa3hkU5j/rOgah3GtTVCuBGsdntte/nyzbWANjpusdqdXY6H6T6aoS/iGgS5kfLwZFbFeAY6QcAYG3agY176jVxbVql7epqmd3FvI+FE+ullLHJuCZPJ0NHpTevw+6A01zmuEewJo86QNziWHOLpSg4FwzrhZakfSWRTxjPOYMYHCHzru2NIWrhrfyZ0sCtcCaZOSm+M0jG4cztWSicc2ku54YxuVjMefK03RE6z3j+/P6XLoKL0827fmVew0pXfHuY8+7dQQ91+ZxXc0EsOu2/IUWr905LMuEeSL5IJwDGJ4BilvJAshaviZA+VtTreA3JRaE+vtq0zF+x8fuuqHZI0YGuJKAauFN1ULvS7UlGdwQgMnf5okiT75vumB097Mkqz8ULj7KzIUVpZodL/r8seL+fgI=",
 "refresh_token": "M.C560_BL2.0.U.-CrVCPeraUsGVQFNR3kP7XEDmnLO2aKPbPbV7i8X6b4c5GIR3WazsxxrM048fZgxoRcdo8HJ2tgblxnKwfSdBBPHwCcUlMRN3Bso!1RHWffbI0CzI4RBA2hgJ4wXvx2xeoiUqTpLrE57YUz2ceWNmarnEES4y2qc2yofO!UlvHe6E1!CDX3YcDBqn5ochsKxUdU1YCWFQEahuldC3YJBgh5q7E!vGxDmRc!8aji*mJL2DwY64*f3qztaotABsiQk4yfn7wazFFx1MNQu1OXM0VUEVTkiiM*4enI7G5*QOuWbcpacK15SHC*p0ZiMy01cLBlH*VmNSBg7duxnApkhMYT2IdThtOv6mMIXJKx0FJrf*WWuTfbCM!Ox*DrvSLe2c0A$$",
 "expires_at": 1721309410.6397078
}

**Comment by Jakke17** [comment]
Ok Roger,

I will do a clean install of the API registration and the integration and will give you feedback

**Comment by RogerSelwyn** [comment]
Make sure the account you are creating the azure app with is the same one you are logging in with for authentication. To be honest you don't actually need to set up permissions on Azure, it will request them when you authenticate.

**Comment by RogerSelwyn** [comment]
I’ve added diagnostics support in v0.1.0, assuming you have diagnostics turned on on your HA instance you can download a file showing your configuration. It lists the requested (required) permissions and the granted permissions (from your token file). All requested permissions must appear in the granted permissions list.

**Comment by RogerSelwyn** [comment]
That is the diagnostic for HACS, not the calendar. But it may not be able to do the diagnostic until you get it installed properly. 

If your token file doesn’t have the permissions in it, then it is likely the account you are authenticating with isn’t the one that you created the app with.

**Comment by RogerSelwyn** [comment]
Back from a walk. I would logout of MS world before doing the authentication, to ensure you are using the right credentials. 

If you really can't figure and need a screen share, let me know.

**Comment by Jakke17** [comment]
Hello Roger,

this weekend I tested with a completely new O365 account. Still the same error.
Googled and used chatgpt to serach for an solution.

maybe we can do an screen share.

**Comment by RogerSelwyn** [comment]
Email me - firstnamesurname @ hotmail

**Comment by RogerSelwyn** [comment]
Problem resolved via a screen share

**Comment by DeCodeerHeer** [comment]
> Problem resolved via a screen share

Running into the same issue, what was the solution?

**Comment by RogerSelwyn** [comment]
I don't remember the issue, but are you using a personal account and have filled in an email address into the shared email address box in the configuration?

**Comment by DeCodeerHeer** [comment]
Thanks for the quick response! Yes I am using a personal account and I have filled in an email address in the shared email address box.

**Comment by RogerSelwyn** [comment]
The shared email address box is for entering the email address of an email account that has been 'shared' with you. As a personal account, nothing can be shared with you, therefore you shouldn't fill that box in.

**Comment by DeCodeerHeer** [comment]
Removed the email address from that box in the configuration, and everything is working like a charm now. Thanks a lot!
