### ISSUE TITLE
Authorizing Issue

### ISSUE THREAD

**Issue by mdb17** [RogerSelwyn/MS365-Calendar#20]
Hey love the effort in this.

I am trying to get setup but can't make it past authorizing.

I get the following no matter what I try:
![image](https://github.com/user-attachments/assets/a6128cc9-d330-42b7-8616-84e2fa80257e)

![image](https://github.com/user-attachments/assets/d7f4d0b1-3ea1-4cb6-b53d-247bd59d1c67)
I feel like I have set all the permissions correctly and have tried the config flow multiple times making sure to delete the token each time.

**Comment by RogerSelwyn** [comment]
I would suspect you have put your email address in the shared_mailbox field, which is only intended if you want to access a shared mailbox. Your image implies you have a personal email address (such as outlook) so you are unlikely to have access to a shared mailbox.

**Comment by mdb17** [comment]
Hey that was it thank you very much. We have a family group and I was thinking that I might need it entered to get the calendar but I didn;t.

**Comment by mdb17** [comment]
Hey that was it thank you very much. We have a family group and I was thinking that I might need it entered to get the calendar but I didn't.

**Comment by RogerSelwyn** [comment]
https://github.com/RogerSelwyn/MS365-Calendar/commit/06987394febdccbd2282bdaf2cdb19f52e2b62b4
