### ISSUE TITLE
Alternate Authentication not possible

### ISSUE THREAD

**Issue by kleinerhobbit** [RogerSelwyn/MS365-Calendar#3]
My HA instance is available from I-Net.

The error tells me, the Redirect URI missmatches with the configured one on the registered App.

Maybe you can take a look at this.

Cheers
Matt

**Comment by RogerSelwyn** [comment]
With you providing almost no information, it is impossible to look at anything.

- Has it worked with O365 integration?
- What uri have you put on the Azure app?
- What url are you accessing the HA instance by when you are trying to authenticate?
- Why not use the simpler non-alternate method?
