### ISSUE TITLE
New setup, not able to create new app registration

### ISSUE THREAD

**Issue by KHV8** [RogerSelwyn/MS365-Calendar#30]
I get this message, when I try to create a new app registration
![image](https://github.com/user-attachments/assets/7c7cbd36-2a4c-466c-8af8-8326e7129186)

Is this something new, or do I need a developer account?

**Comment by RogerSelwyn** [comment]
I think it started in July. If you have an existing app registration I think you can use it. 

Someone was working through it a few days ago - https://github.com/RogerSelwyn/O365-HomeAssistant/issues/255
