### ISSUE TITLE
Migrating from o365 - some calendars unmanageable

### ISSUE THREAD

**Issue by SGXander** [RogerSelwyn/MS365-Calendar#46]
Hi,
Firstly thank you for your efforts on these projects.

I've installed and configured the ms365-calendar and set up with the same details as the o365 version. They are currently running side by side however the ms365 version has 2 out of the 4 calendars marked as "unmanageable". I've not detected any reason this causes a functional issue but thought it worth mentioning.

![image](https://github.com/user-attachments/assets/4b824a66-9161-46c5-911b-478607a0cc6a)

Thanks
SGXander

**Comment by RogerSelwyn** [comment]
Are those calendars correctly updating? My guess is that they are no longer being provided by the integration, so, disabled in some way. 

Have you disabled them in calendars.yaml? Any errors in the logs?

**Comment by SGXander** [comment]
I  hadn't removed any of the old ones. after approximately an hour they lost that symbol and were all managed by the new integration and I have now restarted again removing the old one and supporting config file elements. Seems it was just patience needed!

**Comment by RogerSelwyn** [comment]
Phew, glad it is working. You will have new entity names, I changed them so they are consistent across integrations.
