### ISSUE TITLE
Cannot connect anymore

### ISSUE THREAD

**Issue by DanielStockinger** [RogerSelwyn/MS365-Calendar#48]
Hello, 

i hat the o365 integration and erything has worked as expected. 
now i decided to move forward to the ms-365-Calendar integration.

created a new app registration
![image](https://github.com/user-attachments/assets/e4bec02a-7f40-4918-b4b5-c2cfd8b0d0b8)
![image](https://github.com/user-attachments/assets/9b3b43bd-b07b-4dc4-8833-3755202ce5f0)

cerated a new client secret
have set the permissions as documented

![image](https://github.com/user-attachments/assets/a6415a20-1994-4e93-9995-daab1401d40d)

link M365 Account works fine
but during submit i get this error, but calendars.ReadWrite.Shared  permissions are set
![image](https://github.com/user-attachments/assets/2a77fff9-8f91-47dc-ad61-fc4470649e5e)

![image](https://github.com/user-attachments/assets/92515e2b-ed7c-4010-b1b3-66f8c272f7a4)

Many Thanks for your help
Daniel

**Comment by RogerSelwyn** [comment]
Remove the email address you have put in the shared mailbox field. I assume you don’t want to access a shared mailbox?

**Comment by DanielStockinger** [comment]
@RogerSelwyn  wow that works. Thank you so much. I agree that was my mistake.

**Comment by RogerSelwyn** [comment]
Just checking. Is yours a personal account? Just trying to think why it don’t pick up that you granted that permission. Need to give a more meaningful error.

**Comment by DanielStockinger** [comment]
Hello Roger, 

yes it is my personal office account. 
I was always watching and searching regarding permissions issues.

**Comment by RogerSelwyn** [comment]
I think you can't use personal for shared account, but I don't think I've got anyway of spotting that it is a personal account, and therefore shared permissions won't work.

**Comment by RogerSelwyn** [comment]
Need to try to figure a way to capture this.Maybe by retrieving email address for the account, and then comparing to "shared" email address, and reject if the same.

**Comment by DanielStockinger** [comment]
maybe a nother issue?

this is my calender configuration:

```
- cal_id: XXASDJASLDKJALKSDJLA
  entities:
  - device_id: Your family
    end_offset: 24
    name: Your family
    start_offset: 0
    track: true
```

and what i read from the documentation i should get the elements from the data object

The data attribute provides an array of events for the period defined by the start_offset and end_offset in ms365_calendars_<entity_name>.yaml. Individual array elements can be accessed using the template notation states.calendar.<entity_name>_calendar.attributes.data[0...n].

```
{% set events = state_attr('calendar.micosoft_365_calendar_std_your_family', 'data') %}
Total events: {{ events | length }}
````
give me a result of 1, what is not correct
Total events: 1

![image](https://github.com/user-attachments/assets/e5c8d5c6-ec0e-4ce3-a0eb-355451103987)

sorry for cross posting :-)

**Comment by RogerSelwyn** [comment]
That implies there is only 1 event in the next 24 hours

**Comment by DanielStockinger** [comment]
thank you so much. 
You are right, i thought 24 are 24 events. i set up to 720 and get 17 events. 
Many Thanks Roger

**Comment by DanielStockinger** [comment]
> Ana thanks for the coffee :-)

you are welcome. Thank you

**Comment by RogerSelwyn** [comment]
The data attribute provides an array of events for the **period defined by the start_offset and end_offset** 

:-)

**Comment by RogerSelwyn** [comment]
I've added a process that checks if shared_email is the same as logged in user, and then removes the attribute from the config. This will be in the next release.

The check happens after authentication (and token retrieval), because it is only then that it is known what the email address of the logged in user is.

**Comment by RogerSelwyn** [comment]
The change will be in the next 1.1.x release

**Comment by RogerSelwyn** [comment]
I have released a new version with this change in it.
