### ISSUE TITLE
Connection Pool is full 

### ISSUE THREAD

**Issue by Snowrisk** [RogerSelwyn/MS365-Calendar#5]
Hello,
The following message appear daily in my Home Assistant log file.

```
`Logger: urllib3.connectionpool
Quelle: /usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py:323
Erstmals aufgetreten: 24. Juni 2024 um 16:11:33 (5281 Vorkommnisse)
Zuletzt protokolliert: 13:56:35

Connection pool is full, discarding connection: graph.microsoft.com. Connection pool size: 10
Connection pool is full, discarding connection: login.microsoftonline.com. Connection pool size: 10`

```
Your integration is the only one that communicates with MS365, so I am opening an issue here.

The error did not occur with your other integration O365.

Thanks 
Jens

**Comment by RogerSelwyn** [comment]
How many calendars are you retrieving?

**Comment by Snowrisk** [comment]
14 🙄
________________________________
Von: RogerSelwyn ***@***.***>
Gesendet: Dienstag, 25. Juni 2024 14:19
An: RogerSelwyn/MS365-Calendar ***@***.***>
Cc: Jens ***@***.***>; Author ***@***.***>
Betreff: Re: [RogerSelwyn/MS365-Calendar] Connection Pool is full (Issue #5)


How many calendars are you retrieving?

**Comment by RogerSelwyn** [comment]
Do you really need 14?

**Comment by RogerSelwyn** [comment]
I’ll take a look when I get back from holiday inn a couple of weeks

**Comment by Snowrisk** [comment]
Thank you and have a nice vacation!
________________________________
Von: RogerSelwyn ***@***.***>
Gesendet: Mittwoch, 26. Juni 2024 03:51
An: RogerSelwyn/MS365-Calendar ***@***.***>
Cc: Jens ***@***.***>; Author ***@***.***>
Betreff: Re: [RogerSelwyn/MS365-Calendar] Connection Pool is full (Issue #5)


I’ll take a look when I get back from holiday inn a couple of weeks

**Comment by RogerSelwyn** [comment]
> Yes, my problem is that automations with a trigger "calendar event" for all-day appointments unfortunately do not work if I only search for certain terms in the appointment title. 

Back from holiday...

Is this only for all day events? i.e. it will work for non-all-day events. Maybe this is because all-day events by default in MS are marked as "Free" rather than "Busy".

To be honest I don't use the HA Automation platform (it's too obscure for me), I use Node Red. That said I suspect the issue is really in whatever HA core is doing, since if this works for non-all-day events then I'd expect it to work for all-day as well.

To re-work this so that it will handle large numbers of calendars is a major task. A simpler route you can take to get your setup to work (assuming no HA core fix) is to duplicate your account in your config with a different account name.

So:
```yaml
o365:
  accounts:
    - account_name: first
      client_id: my_client_id
      client_secret: my_client_secret
      ....
    - account_name: second
      client_id: my_client_id
      client_secret: my_client_secret
      ....
```

This would create a second o365 calendars yaml, where you can put half your device_ids.

**Comment by Snowrisk** [comment]
Thanks, Roger.
I will try it with a 2nd configuration.

________________________________
Von: RogerSelwyn ***@***.***>
Gesendet: Montag, 8. Juli 2024 12:54
An: RogerSelwyn/MS365-Calendar ***@***.***>
Cc: Jens ***@***.***>; Author ***@***.***>
Betreff: Re: [RogerSelwyn/MS365-Calendar] Connection Pool is full (Issue #5)


Yes, my problem is that automations with a trigger "calendar event" for all-day appointments unfortunately do not work if I only search for certain terms in the appointment title.

Back from holiday...

Is this only for all day events? i.e. it will work for non-all-day events. Maybe this is because all-day events by default in MS are marked as "Free" rather than "Busy".

To be honest I don't use the HA Automation platform (it's too obscure for me), I use Node Red. That said I suspect the issue is really in whatever HA core is doing, since if this works for non-all-day events then I'd expect it to work for all-day as well.

To re-work this so that it will handle large numbers of calendars is a major task. A simpler route you can take to get your setup to work (assuming no HA core fix) is to duplicate your account in your config with a different account name.

So:

o365:
  accounts:
    - account_name: first
      client_id: my_client_id
      client_secret: my_client_secret
      ....
    - account_name: second
      client_id: my_client_id
      client_secret: my_client_secret
      ....

This would create a second o365 calendars yaml, where you can put half your device_ids.
