### ISSUE TITLE
Problem after re-install

### ISSUE THREAD

**Issue by Largus72** [RogerSelwyn/MS365-Calendar#51]
Hi,

I'm trying to add another account,  but got the message in attached screenshot.
Name I want to use is different from first time I added the migration, but it is a name I used before in a test.
After the test I removed the integration to try again.

![Schermafbeelding 2024-12-20 205456](https://github.com/user-attachments/assets/3f26d166-ad53-4655-a906-2938395b87c1)

Onno

**Comment by RogerSelwyn** [comment]
I'll need to take a look at that. You can look in ./storage/config_entries.json and you will probably find a deleted config entry you can remove which will enable you to re-use.

**Comment by Largus72** [comment]
Hi Roger,

Thanks!
Works like a charm.
Deleted the tokens (and yaml files) from ms365_storage and adding extra accounts is going fine.
A tip: empty browsercache before adding an extra account, otherwise, the link to an account link will auto login witht the first account used before.

Thanks again. Great integration.

Onno

**Comment by RogerSelwyn** [comment]
Thanks for confirming how you fixed it. I've added a process to delete the token and yaml file when the config entry is removed. This will be in the next release.

**Comment by RogerSelwyn** [comment]
I should have said, it will be in the next 1.1.x release

**Comment by RogerSelwyn** [comment]
I have released a new version with this change in it.
