### ISSUE TITLE
problem with date format in events creation "time data '20250203' does not match format '%Y%m%dT%H%M%S'"

### ISSUE THREAD

**Issue by goldriver2** [RogerSelwyn/MS365-Calendar#52]
I tried to create an event via the UI for an all day event recuring every other week with a end date of 2/3/2025 and got the following error:

_time data '20250203' does not match format '%Y%m%dT%H%M%S'_

![image](https://github.com/user-attachments/assets/8a4e33d8-77a1-4fef-84ab-0a433c6869a0)

- system set to metric, country canada and language french
- HA OS 14.1
- Supervisor 2024.12.0
- Micosoft 365 - Calendar 1.0.1

I have no problem if i create an event without repeat ending dates

**Comment by RogerSelwyn** [comment]
Should be fixed with v1.0.2 - https://github.com/RogerSelwyn/MS365-Calendar/releases/tag/v1.0.2

**Comment by goldriver2** [comment]
Definitly is fixed in 1.0.2, thanks
