### ISSUE TITLE
Unable to Add Event from Calendar UI

### ISSUE THREAD

**Issue by ZinTheDog** [RogerSelwyn/MS365-Calendar#53]
I'm not able to add events from the Calendar UI and can only see the option to add events to local calendars.  Read seems to be no problem at all, I can see all of my events, I just can't create anything new.  No obvious errors seen in the logs, all authentication and permissions seem correct and happy.  Calendar entities are visible for all calendars my M365 account has access to, including one on a Shared Mailbox.

Any thoughts or help on where I may be going wrong, or additions items to check?  Thank you!

(The calendar option in the screenshot below is a local calendar - I blocked out the details for privacy).
![image](https://github.com/user-attachments/assets/36a6220b-adde-4d44-86e7-dd4853de1039)

Read/Write Permissions show Calendar.ReadWrite.Shared granted w/ user consent.
![image](https://github.com/user-attachments/assets/92d73e01-aeab-41b0-9b6b-fc3adb5e28ff)

List of all Calendar Entities from the Microsoft 365 - Calendar integration.  None of these are options in the Calendar UI to select when adding an Event.
![image](https://github.com/user-attachments/assets/650fd345-0a5d-44bb-a2e8-a780a7906224)

**Comment by RogerSelwyn** [comment]
Did you enable update in the initial configuration of the module?

https://rogerselwyn.github.io/MS365-Calendar/installation_and_configuration.html#configuration-variables

If not, reconfigure (by clicking on the three dots), and check enable update. You will need to re-authenticate.

**Comment by ZinTheDog** [comment]
Hi Roger, thank you for the quick reply!  Yes, "Enable Update Services" is checked, and was on the original configuration: 
![image](https://github.com/user-attachments/assets/2c4d81ee-a738-4000-a71d-508d7864cbf8)

**Comment by RogerSelwyn** [comment]
Can you post the diagnostic from the integration. There shouldn’t be any sensitive info in it, but can you check.

**Comment by RogerSelwyn** [comment]
I can't duplicate the issue which is why I'm suggesting providing the diagnostic. However, I have found an issue in the underlying library which _may_ cause a problem (the owner of the library is deign some major re-work on authentication which I am testing, so I don't know if the issue pre-dates his updates), for which I would suggest as a workaround to delete the token and re-authenticate

**Comment by ZinTheDog** [comment]
> Can you post the diagnostic from the integration. There shouldn’t be any sensitive info in it, but can you check.

Diagnostics file below - I redacted a few things because of the names I used on the calendars, but the core data is all there.
[config_entry-ms365_calendar-2024.12.29.json](https://github.com/user-attachments/files/18270223/config_entry-ms365_calendar-2024.12.29.json)

Steps I took to delete the token and re-authenticate:
1. Deleted Integration Entry for M365 Calendar.
2. Navigated with Visual Studio to /config/m365_storage/ and deleted: ./m365_calendars_X.yaml and /.ms365-token-cache/ms365_calendar.token files.
3. Re-ran through adding the Microsoft 365 - Calendars integration and authenticating.  (Enable update services is checked again).

Authentication was a success: 
![image](https://github.com/user-attachments/assets/c907af15-bbf0-4db1-90d5-efd3140712da)

I can see all 4 of my calendars again (including one that's on a shared mailbox) but still cannot create events in the Calendars UI.  Please let me know if there is anything else I can provide that may help.  Thank you!

**Comment by RogerSelwyn** [comment]
Can you check if the ms365 'actions` exist. You can check this in the Developer Tools/Actions tab. At the moment I can't see why the calendars would be unavailable to add events.

**Comment by ZinTheDog** [comment]
> Can you check if the ms365 'actions' exist. You can check this in the Developer Tools/Actions tab. At the moment I can't see why the calendars would be unavailable to add events.

They do not appear to be there: 
![image](https://github.com/user-attachments/assets/86fcf37f-7d38-4b76-b7d5-7c3c478bc8e3)

I see the normal Calendar.create_events & Calendar.get_events:
![image](https://github.com/user-attachments/assets/c740ce65-0e85-495c-9056-6d232169de5e)

**Comment by RogerSelwyn** [comment]
Look for Ms365_calendar actions

**Comment by ZinTheDog** [comment]
> Look for Ms365_calendar actions

None:
![image](https://github.com/user-attachments/assets/b072fd61-3b1d-4a02-b0a1-a112ccc71aed)

**Comment by RogerSelwyn** [comment]
I’m making the assumption you have rebooted ha.

**Comment by RogerSelwyn** [comment]
We may need to have a debugging session. Not today…

**Comment by ZinTheDog** [comment]
> I’m making the assumption you have rebooted ha.

Yup, rebooting now for good measure anyway.  I also deleted and re-created the Entra ID App Registration before opening the issue here.  When I read though the MFA section of your documentation, I also added the secondary URI of "https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize" since my Entra ID account is using MFA too.

**Comment by ZinTheDog** [comment]
> We may need to have a debugging session. Not today…

Sounds good, thank you!  Enjoy the rest of your Sunday.  I will be around most of the week so let me know when it's a good time.

Also, fresh reboot completed, no change in behavior.

**Comment by RogerSelwyn** [comment]
> When I read though the MFA section of your documentation, I also added the secondary URI of "https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize" since my Entra ID account is using MFA too.

That shouldn't be the issue, since that is authentication. Provision of services is controlled by my code.

**Comment by RogerSelwyn** [comment]
Should have asked, what version of the integration are you using.

**Comment by ZinTheDog** [comment]
> Should have asked, what version of the integration are you using.

v1.0.2

![image](https://github.com/user-attachments/assets/6c667ecc-91b8-450b-afb8-19e469819585)

**Comment by RogerSelwyn** [comment]
Should be fixed with v1.0.3 - https://github.com/RogerSelwyn/MS365-Calendar/releases/tag/v1.0.3

**Comment by ZinTheDog** [comment]
> Should be fixed with v1.0.3 - https://github.com/RogerSelwyn/MS365-Calendar/releases/tag/v1.0.3

You nailed it, the M365 Calendars are available to create events on and the actions are also provisioned now too.  Thank you!

**Comment by jameslshannon** [comment]
Hi Roger - adding here as looks related...

I installed 1.0.3 earlier today and am seeing 403s in the log when trying to update or create events - read is fine.

Updates are enabled, read/write API permissions look good in Entra ID and ms365 actions are available in HA. Let me know if there's anything else you need other than diagnostics and log excerpt below.

Many thanks,

James

--

[O365.connection] Client Error: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/me/events/<snip> | Error Message: Access is denied. Check credentials and try again.

[config_entry-ms365_calendar-01JGBSQ2CCDJ5CG9CKPPASQ52J.json](https://github.com/user-attachments/files/18277387/config_entry-ms365_calendar-01JGBSQ2CCDJ5CG9CKPPASQ52J.json)

**Comment by RogerSelwyn** [comment]
Have you tried going back to 1.0.2 and whether that resolves the issue?

**Comment by RogerSelwyn** [comment]
Also post the full error, there will be more to it

**Comment by jameslshannon** [comment]
Reverted to 1.0.2 and same issue - full log below for modify then create (same error) using 1.0.3

Thanks

[home-assistant.log](https://github.com/user-attachments/files/18277463/home-assistant.log)

**Comment by RogerSelwyn** [comment]
I would delete your token and yaml file, therefore you shouldn't reconfigure and reauthenticate

**Comment by jameslshannon** [comment]
OK, did that and same issue, but....have since discovered that it's calendar-specific - create/edit works fine for another user's calendar shared by the logged in user, but not for a calendar of the logged in user. I therefore assume this relates to calendar permissions on this specific calendar?

**Comment by RogerSelwyn** [comment]
Sounds like for some reason you don’t have permission to the calendar. If you have granted calendars.ReadWrite and possibly calendars.ReadWrite.Shared (but you shouldn’t need that with your config) then it should work. You can test the calls via ms graph explorer to be sure.

**Comment by RogerSelwyn** [comment]
Make sure you have refreshed your browser cache and aren’t trying to do updates against an unavailable/restored state calendar.

**Comment by RogerSelwyn** [comment]
You can't edit a birthday or national holiday calendar.

**Comment by jameslshannon** [comment]
Cache disabled, fresh browser session and no birthday/national holiday calendars involved. Strange thing is that the calendars that aren't working are the logged in user's own calendars that they maintain using Outlook every day (full read-write) vs the ones that are working which are shared with them by me with View only (no edit) permissions! Am going to check their calendar permissions in Outlook for anything strange...assuming that could be a factor?

**Comment by RogerSelwyn** [comment]
No idea. Check using this url https://graph.microsoft.com/v1.0/me/calendars in graph explorer. There seems to be a field in each calendar returned saying if it can be updated. But bear in mind that would be using your own credentials rather than via the app.

**Comment by RogerSelwyn** [comment]
canEdit seems to birthday/national holiday calendars. Can't see why your personal calendar wouldn't be accessible

**Comment by jameslshannon** [comment]
canEdit attributes look fine for the logged in user via graph explorer but are the opposite to what's actually editable, but I think I've figured out what's going on...

When I login as the end user I'm also asked for an admin login for Entra ID to approve the access, however it seems to be the identity of the admin user that's returned in the URL manually added to the HA config - not the identity of the user logging in. Hence why I'm able to edit my calendars and not theirs!

I was going to try the alternative login method to see if that handles the redirect back to the original logged in user correctly but can't find the documented "Use alternate authentication" setting in Entra ID - has this moved or changed name?

**Comment by jameslshannon** [comment]
Logged out of all MS accounts, tried a different browser and even a different PC, but the redirect URL always seems to represent the admin approver (second login prompt) not the logged in user (first login prompt).

In the end I worked around it by temporarily giving the logged in user the "Application Administrator" role in Entra ID which allows them to approve (avoiding a second admin login) and therefore their login to be represented in the final redirect URL.

Thanks for your help troubleshooting - all working as expected now!

**Comment by jameslshannon** [comment]
One small thing I just noticed...when I create a new event the default calendar in the dialog is one with canEdit = false so always errors unless you change it to one that has canEdit = true (which users aren't necessarily aware of).

If possible, it would be great to omit any calendars from the create event dialog where canEdit = false to avoid users getting the "unknown error" when clicking Add Event (and also having to select another calendar every time they create an event). Alternatively being able to select a default calendar for event creation would also avoid this.

I guess the same goes for disabling the Edit/Delete Event link for any calendars where canEdit = false to avoid 'false' errors.

Thanks again for a great integration!

**Comment by RogerSelwyn** [comment]
> If possible, it would be great to omit any calendars from the create event dialog where canEdit = false to avoid users getting the "unknown error" when clicking Add Event (and also having to select another calendar every time they create an event). Alternatively being able to select a default calendar for event creation would also avoid this.

That's what I was planning. I have a major release in the works, so it would be in that.

**Comment by RogerSelwyn** [comment]
> > If possible, it would be great to omit any calendars from the create event dialog where canEdit = false to avoid users getting the "unknown error" when clicking Add Event (and also having to select another calendar every time they create an event). Alternatively being able to select a default calendar for event creation would also avoid this.
> 
> That's what I was planning. I have a major release in the works, so it would be in that.

I've added this protection, it will be in the next 1.1.x release

**Comment by RogerSelwyn** [comment]
I have released a new version with this change in it. A future major release will ad further improvements

**Comment by jameslshannon** [comment]
Works great - thanks Roger!
